package network;

public enum PacketType {
    CLIENT_INIT,
    TEAMS_AVAILABLE,
    JOIN_REQUEST, JOIN_REQUEST_ACCEPTED,
    PING,
    LEVEL_TURN_UPDATE, CLIENT_END_TURN,
    CLIENT_REQUEST_LEVEL_DATA,
    UNIT_UPDATE,
    ENERGY_UPDATE,

    CLIENT_REQUEST_MOVE_UNIT,
    SERVER_MOVE_UNIT,
    CLIENT_REQUEST_SHOOT_UNIT,
    SERVER_SHOOT_UNIT,
    CLIENT_REQUEST_CAPTURE_UNIT,
    SERVER_CAPTURE_UNIT,
    SERVER_STRUCTURE_UPDATE,
    CLIENT_REQUEST_SHIELD_REGEN,
    SERVER_SHIELD_REGEN,
    CLIENT_REQUEST_STEALTH,
    SERVER_STEALTH_UNIT
}
